name: Windows

on:
  push:
    branches: [ "winbuild" ]
    paths-ignore:
      - 'src/docs/**'
      - 'src/main/java/**'
  pull_request:
    branches: [ "winbuild" ]
    paths-ignore:
      - 'src/docs/**'
      - 'src/main/java/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Default
            triplet: x64-windows
            arch: x64
            build-type: Debug
            generator: "Ninja"

    runs-on: windows-latest
    timeout-minutes: 30
    name: ${{ matrix.name }}
    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: winbuild
      - name: Build
        shell: cmd
        run: |
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
            cd src/native/windows/apps/prunsrv
            nmake CPU=X64
            cd src/native/windows/apps/prunmgr
            nmake CPU=X64
      - name: Test
        shell: cmd
        run: |
            cd src/native/windows/apps/prunsrv/test/scripts
            test.bat
